name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Load node_modules from cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package.json') }}

      - name: Load libs from cache
        uses: actions/cache@v2
        with:
          path: packages/*/lib
          key: ${{ runner.os }}-lib-${{ github.sha }}

      #- run: npm run release:publish
      - run: echo 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}